### ISSUE TITLE
可以考虑添加高德地图

### ISSUE THREAD

**Issue by hubutui** [CubicPill/OPR-tools-CN#3]
高德地图的单点标注可以参考 [高德地图 URI API](http://lbs.amap.com/api/uri-api/guide/mobile-web/point)．

然后有个小问题要请教一下，关于坐标转换，我看到你是用的 [coordtransform](https://github.com/wandergis/coordtransform)．我自己有个修改版本 [opr-tool-china](https://github.com/hot123tea123/opr-tools-china)，考虑到高德地图和百度地图的 URI API 都可以指定坐标类型为 GPS，我就没有进行火星坐标转换．但是腾讯地图虽然也可以指定，但是实际上并没用，这是腾讯的锅，没办法我才用 [eviltransform](https://github.com/googollee/eviltransform) 进行转换的．不知道这两个转换的结果会不会有准确度的问题？

**Comment by CubicPill** [comment]
谢谢建议, 已经增加了高德地图按钮. 转换后坐标的精度我有试验过, 误差一般在 2~3m 内, 不影响使用
