### ISSUE TITLE
标题或者描述包含 agent id 并不用直接拒吧

### ISSUE THREAD

**Issue by hubutui** [CubicPill/OPR-tools-CN#5]
我记得标准里并没有说标题不合适就直接拒的啊，还是在标题那里打一星比较合适．可以等上线后由玩家修改啊．

**Comment by CubicPill** [comment]
这个主要是参考了 Ingress 的 [Candidate Portal criteria](https://support.ingress.com/hc/en-us/articles/207343987-Candidate-Portal-criteria) 中的 **Guidelines for Portal titles** 部分    
>Please do not include real names, codenames, faction or group names in titles     

考虑到目前 Portal Edit 得到答复的时间很长, 以及猩猩魔幻的通过标准, 我个人的标准是标题有人名, 位置偏移严重, 或者看起来明显不安全的 po 直接一星拒掉. 如果下一版 OPR 有了修改标题和描述的功能, 我会把这个按钮去掉. 位置的问题也是这样, 如果猩猩加了 review suggested location 的功能, 我也会把位置不准确的按钮去掉

**Comment by hubutui** [comment]
个人觉得因为标题/描述不太合适就直接拒还是比较可惜的．另外位置的话，审核的玩家本来就应该要确认位置，若有偏移应该根据街景地图等修正的，直接拒的只适合移位假 po 吧．

**Comment by CubicPill** [comment]
好的, 这两个按钮保留与否我会收集一下意见, 如果使用频率不高的话我会在下一版里面去掉, 谢谢你的提议
