### ISSUE TITLE
开GFWList PAC的时候不能加载

### ISSUE THREAD

**Issue by LQBing** [CubicPill/OPR-tools-CN#6]
RT

**Comment by CubicPill** [comment]
请提供一下重现方法, 以及详细描述一下问题 (最好有页面截图和控制台错误信息), 谢谢

**Comment by LQBing** [comment]
等很久也可以加载出来，发现是部分url未走代理导致超时，一定要超时后才会加载界面。我尝试了在user-rule.txt里添加下面信息就可以了。如果改成先渲染主要部分，一些不是很重要部分的数据进行延迟渲染的话会不会好点？

*.google.cn
*.google-analytics.com
||translate.google.cn
||ingress.com
||csi.gstatic.com
||maps.googleapis.com
www.openstreetmap.org

**Comment by CubicPill** [comment]
插件并没有加载多余页面内容, 添加的都是指向外部网页的超链接, 按理说不应该存在显著拖慢加载速度的原因       
可以确定 google-analytics.com csi.gstatic.com maps.googleapis.com 是猩猩的锅, 其他链接的确在插件中出现过, 但并没有进行相应的页面加载     
原版网页也会存在此类问题么?

**Comment by LQBing** [comment]
原版会出现，但是猩猩直接白菊花让人等

**Comment by CubicPill** [comment]
我试了一下没法重现, 开着插件的情况下白菊花不会消失. 建议把相关网站加入强制代理列表
